### ISSUE TITLE
"escape" is breaking build?

### ISSUE THREAD

**Issue by MrCotelandia** [christian-fei/Simple-Jekyll-Search#76]
`"simple-jekyll-search": "^1.2.0"`

Search.json
![screenshot from 2017-06-28 11-11-47](https://user-images.githubusercontent.com/2418915/27641613-c32dd520-5bf2-11e7-8fff-480f97b574c2.png)

```
user@pc:~/Documents/proyecto$ gulp
[11:20:08] Using gulpfile ~/Documents/proyecto/gulpfile.js
[11:20:08] Starting 'sass'...
[11:20:08] Starting 'js'...
[11:20:08] Finished 'js' after 2.53 ms
[11:20:08] Starting 'jekyll-build'...
Configuration file: _config.yml
            Source: /home/user/Documents/proyecto
       Destination: /home/user/Documents/proyecto/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
[11:20:09] Finished 'sass' after 681 ms
  Liquid Exception: no implicit conversion of Integer into String in search.json
jekyll 3.5.0 | Error:  no implicit conversion of Integer into String
[11:20:10] 'jekyll-build' errored after 1.26 s
[11:20:10] Error: 1
    at formatError (/home/user/.nvm/versions/node/v8.1.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/home/user/.nvm/versions/node/v8.1.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:115:13)
    at Gulp.emit (events.js:210:7)
    at Gulp.Orchestrator._emitTaskDone (/home/user/Documents/proyecto/node_modules/orchestrator/index.js:264:8)
    at /home/user/Documents/proyecto/node_modules/orchestrator/index.js:275:23
    at finish (/home/user/Documents/proyecto/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/user/Documents/proyecto/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
```

If I remove ` | escape ` from `"title" : "{{ post.title | escape }}",` (search.json) works fine.

**Comment by christian-fei** [comment]
Hello,
thanks for reporting.
Did you manage to get it working?
